create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  avatar_url text,
  coins bigint not null default 0 check (coins >= 0),
  superlive_user_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Profiles are readable by authenticated users" on public.profiles;
create policy "Profiles are readable by authenticated users"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "Users update their own profile" on public.profiles;
create policy "Users update their own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Financial balance is read-only to browser clients. Credit it only from a
-- trusted payment webhook using the Supabase service role.
revoke update on public.profiles from authenticated;
grant update (full_name, avatar_url, superlive_user_id) on public.profiles to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute procedure public.set_updated_at();

create table if not exists public.payment_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete restrict,
  provider text not null default 'vizzion_pay',
  provider_transaction_id text unique,
  external_reference text not null unique,
  package_id text not null,
  coins bigint not null check (coins > 0),
  bonus bigint not null default 0 check (bonus >= 0),
  amount numeric(12, 2) not null check (amount > 0),
  currency text not null default 'BRL',
  method text not null check (method in ('pix', 'credit_card')),
  status text not null default 'created',
  offer_code text,
  checkout_url text,
  customer_name text,
  customer_email text,
  customer_phone_last4 text,
  customer_document_last4 text,
  billing_address jsonb not null default '{}'::jsonb,
  card_brand text,
  card_last4 text,
  provider_fee numeric(12, 2) not null default 0 check (provider_fee >= 0),
  operational_cost numeric(12, 2) not null default 0 check (operational_cost >= 0),
  refunded_amount numeric(12, 2) not null default 0 check (refunded_amount >= 0),
  webhook_token_hash text,
  provider_payload jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  credited_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.payment_orders
  add column if not exists billing_address jsonb not null default '{}'::jsonb,
  add column if not exists provider_fee numeric(12, 2) not null default 0,
  add column if not exists operational_cost numeric(12, 2) not null default 0,
  add column if not exists refunded_amount numeric(12, 2) not null default 0;

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  order_id uuid references public.payment_orders(id) on delete set null,
  provider text not null default 'vizzion_pay',
  provider_transaction_id text,
  event_type text not null,
  idempotency_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text
);

create table if not exists public.payment_risk_assessments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.payment_orders(id) on delete cascade,
  provider text not null,
  provider_reference text,
  score numeric(5, 2) check (score >= 0 and score <= 100),
  decision text not null check (decision in ('pending', 'approved', 'review', 'rejected')),
  signals jsonb not null default '{}'::jsonb,
  assessed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists payment_orders_user_created_idx
  on public.payment_orders (user_id, created_at desc);
create index if not exists payment_orders_offer_email_idx
  on public.payment_orders (offer_code, customer_email, created_at desc);
create index if not exists payment_orders_status_created_idx
  on public.payment_orders (status, created_at desc);
create index if not exists payment_events_transaction_idx
  on public.payment_events (provider_transaction_id, received_at desc);
create index if not exists payment_risk_order_idx
  on public.payment_risk_assessments (order_id, assessed_at desc);

alter table public.payment_orders enable row level security;
alter table public.payment_events enable row level security;
alter table public.payment_risk_assessments enable row level security;

drop policy if exists "Users read their own payment orders" on public.payment_orders;
create policy "Users read their own payment orders"
on public.payment_orders for select
to authenticated
using (auth.uid() = user_id);

revoke insert, update, delete on public.payment_orders from anon, authenticated;
revoke all on public.payment_events from anon, authenticated;
revoke all on public.payment_risk_assessments from anon, authenticated;

drop trigger if exists payment_orders_set_updated_at on public.payment_orders;
create trigger payment_orders_set_updated_at
  before update on public.payment_orders
  for each row execute procedure public.set_updated_at();

create or replace function public.process_vizzion_payment_event(
  p_event_type text,
  p_provider_transaction_id text,
  p_external_reference text,
  p_offer_code text,
  p_checkout_url text,
  p_customer_email text,
  p_status text,
  p_card_brand text,
  p_card_last4 text,
  p_payload jsonb,
  p_idempotency_key text
)
returns table(order_id uuid, order_status text, coins_credited boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_order public.payment_orders%rowtype;
  inserted_event_id bigint;
  should_credit boolean := false;
begin
  insert into public.payment_events (
    provider_transaction_id,
    event_type,
    idempotency_key,
    payload
  ) values (
    nullif(p_provider_transaction_id, ''),
    p_event_type,
    p_idempotency_key,
    coalesce(p_payload, '{}'::jsonb)
  )
  on conflict (idempotency_key) do nothing
  returning id into inserted_event_id;

  if inserted_event_id is null then
    select po.id, po.status, po.credited_at is not null
      into order_id, order_status, coins_credited
    from public.payment_orders po
    where po.provider_transaction_id = nullif(p_provider_transaction_id, '')
       or po.external_reference = nullif(p_external_reference, '')
    order by po.created_at desc
    limit 1;
    return next;
    return;
  end if;

  select po.* into target_order
  from public.payment_orders po
  where (nullif(p_provider_transaction_id, '') is not null
         and po.provider_transaction_id = p_provider_transaction_id)
     or (nullif(p_external_reference, '') is not null
         and po.external_reference = p_external_reference)
     or (nullif(p_offer_code, '') is not null
         and po.offer_code = p_offer_code
         and lower(po.customer_email) = lower(coalesce(p_customer_email, ''))
         and po.credited_at is null)
  order by
    case when po.provider_transaction_id = p_provider_transaction_id then 0
         when po.external_reference = p_external_reference then 1
         else 2 end,
    po.created_at desc
  limit 1
  for update;

  if target_order.id is null then
    update public.payment_events
    set processed_at = now(), processing_error = 'Pedido correspondente nao encontrado'
    where id = inserted_event_id;
    return;
  end if;

  should_credit := p_event_type = 'TRANSACTION_PAID' and target_order.credited_at is null;

  update public.payment_orders
  set provider_transaction_id = coalesce(nullif(p_provider_transaction_id, ''), provider_transaction_id),
      offer_code = coalesce(nullif(p_offer_code, ''), offer_code),
      checkout_url = coalesce(nullif(p_checkout_url, ''), checkout_url),
      status = coalesce(nullif(p_status, ''), status),
      card_brand = coalesce(nullif(p_card_brand, ''), card_brand),
      card_last4 = coalesce(nullif(p_card_last4, ''), card_last4),
      provider_payload = coalesce(p_payload, provider_payload),
      paid_at = case when p_event_type = 'TRANSACTION_PAID' then coalesce(paid_at, now()) else paid_at end,
      credited_at = case when should_credit then now() else credited_at end
  where id = target_order.id;

  if should_credit then
    update public.profiles
    set coins = coins + target_order.coins + target_order.bonus
    where id = target_order.user_id;
  end if;

  update public.payment_events
  set order_id = target_order.id, processed_at = now()
  where id = inserted_event_id;

  order_id := target_order.id;
  order_status := coalesce(nullif(p_status, ''), target_order.status);
  coins_credited := should_credit;
  return next;
end;
$$;

revoke all on function public.process_vizzion_payment_event(
  text, text, text, text, text, text, text, text, text, jsonb, text
) from public, anon, authenticated;
grant execute on function public.process_vizzion_payment_event(
  text, text, text, text, text, text, text, text, text, jsonb, text
) to service_role;

create table if not exists public.private_call_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  streamer_id text not null,
  streamer_name text not null default '',
  streamer_avatar_url text,
  upstream_call_id text,
  status text not null default 'requested'
    check (status in ('requested', 'ringing', 'connected', 'rejected', 'cancelled', 'ended', 'failed')),
  connected_at timestamptz,
  ended_at timestamptz,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  failure_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists private_call_requests_user_created_idx
  on public.private_call_requests (user_id, created_at desc);
create index if not exists private_call_requests_streamer_created_idx
  on public.private_call_requests (streamer_id, created_at desc);

alter table public.private_call_requests enable row level security;

drop policy if exists "Users read their own private calls" on public.private_call_requests;
create policy "Users read their own private calls"
on public.private_call_requests for select
to authenticated
using (auth.uid() = user_id);

revoke insert, update, delete on public.private_call_requests from anon, authenticated;

drop trigger if exists private_call_requests_set_updated_at on public.private_call_requests;
create trigger private_call_requests_set_updated_at
  before update on public.private_call_requests
  for each row execute procedure public.set_updated_at();
